---
title: "How to use the bikr package"
author: "Tim Foster"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

## This vignette will describe how to use the bikr package etc

# Getting started

First you need some bicycle. Type 

``demodata <- scotlandMsp ``

in to the R console and press return. You now have a data object called demodata containing data from Scotland parliament constituencies plus a very examplar cities from around the Europe.

The data has been extracted from the OpenStreetMap dataset. This dataset is provided by thousands of volunteers from around the world. It is a particuarlly good source of data on cycling infrastrucutre and it really the best and only resource of world wide bicycle infrastructure data. It can be patvchy in places but for many coutnries is of a high quality. I thoroughly recommend you try editing OpenStreetMap and adding to the map in your area. By editing OpenStreetMap you will gain a better understanding of the data we are using in this package.

The ``demoData`` dataframe has information about the length of national cycle routes, bicycle parking and the total length of bicycle path in each area. The demo dataset also has supplementary data on the number of people commuting by bicycle. This was gained for census and other information where available. The supplementary data isn't required for any of the functions in the package but we will use it later in the vignette to validate the functions to some extent. 

Now we have some data, we can run our first function:

``demoStatus <- bicycleStatus(demodata)``

The demoStatus object is a dataframe which has classified the 
















